### ISSUE TITLE
Use regexes in config to remove certain OpenAPI paths for PowerShell style

### ISSUE THREAD

**Issue by irvinesunday** [microsoftgraph/microsoft-graph-devx-api#1047]
We need to consider moving the function of removing the problematic paths affecting PowerShell cmdlet generation via AutoREST from XSLT to DevX API (specifically in the `PowerShellFormatter.cs` class in the OpenAPIService). These paths can be removed when formatting the subset OpenAPI document for PowerShell. 
We can make use of a config file (probably _appsettings.json_) with a list of the target paths (regex formatted) that we want removed specifically for PowerShell and use the regex to match and remove them in DevX API before serving the PowerShell-styled OpenAPI documents. Using this alternative, we can go ahead and remove the transforms that were added for these paths in the [preprocess_csdl.xsl](https://github.com/microsoftgraph/msgraph-metadata/blob/master/transforms/csdl/preprocess_csdl.xsl) file in the metadata repo and just continue using the single (unedited) CSDL file to generate OpenAPI documents for all the other styles in DevX API (GEAutocomplete, PowerPlatform and PowerShell). This document should have all the expected paths that were intentionally removed via XSLT (due to one reason or another). This config with a list of the regex-formatted paths can easily be updated from the app service configuration without requiring any re-deployment of the API.

**Comment by zengin** [comment]
@irvinesunday, I love this idea. Not requiring a deployment for a config change will be a great improvement.

I'll be stating the obvious, but as part of the acceptance criteria for this feature, we should make sure that we have a test/review process before deploying the configuration directly to production in order to prevent side effects and regressions. Being able to rollback to a previously known good state and being able to audit changes and history would also be great in order to troubleshoot.

**Comment by millicentachieng** [comment]
This is outdated as conversion to Open API document is no longer done on DevX API.
