### ISSUE TITLE
The examples for this page don't work

### ISSUE THREAD

**Issue by rmencia-isv** [microsoftgraph/microsoft-graph-devx-api#1084]
In the latest nuget packages for the beta, this code doesn't compile anymore. Other examples are also not working.

await graphClient.Users["{user-id}"]
	.Request()
	.UpdateAsync(user);

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bad15fb9-23aa-165f-2dbd-5838c951c5b5
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph beta](https://docs.microsoft.com/en-au/graph/api/user-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-update.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by zengin** [comment]
@maisarissi, we started getting issues like this recently. Are there any plans on clarifying that the generated snippets are for Typewriter-based SDKs?

Especially in beta, I think customers end up picking the kiota-based SDK because everything is marked as preview, and it makes sense to choose the latest. However, docs don't have snippets for kiota-based SDK.
