### ISSUE TITLE
Incorrect cmdlet used for PowerShell snippet converted from the HTTP request.

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/microsoft-graph-devx-api#1353]
**Describe the bug**
The conversion of the HTTP example to PowerShell has resulted to an incorrect cmdlet given the uri of the API.

**To Reproduce**
1. Go to '[Workflow run summary](https://learn.microsoft.com/en-us/graph/api/identitygovernance-run-summary?view=graph-rest-beta&tabs=powershell)'
2. Get the cmdlets for the API URI `/identityGovernance/lifecycleWorkflows/workflows/{workflowId}/runs/summary(startDateTime={timestamp},endDateTime={timestamp})`
3. Click on the first PowerShell example
4. The example has used `Get-MgIdentityGovernanceLifecycleWorkflowRun` instead of `Invoke-MgSummaryIdentityGovernanceLifecycleWorkflowRun`

**Expected behavior**
The example should use `Invoke-MgSummaryIdentityGovernanceLifecycleWorkflowRun` as shown below:

**Screenshots**
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/73849846/216315972-e973faf9-8022-4a94-b601-5054adbbac17.png">

Similar issue with the following pages:

- [Task report summary](https://learn.microsoft.com/en-us/graph/api/identitygovernance-taskreport-summary?view=graph-rest-beta&tabs=powershell)
- [User processing result
](https://learn.microsoft.com/en-us/graph/api/identitygovernance-userprocessingresult-summary?view=graph-rest-beta&tabs=powershell)

**Comment by peombwa** [comment]
The issue seems to be with how DevX API is matching the API path in HTTP request to the path in the source OpenAPI document when generating snippets. The mismatch is happening for all OpenAPI based SDKs, i.e., [Powershell](https://learn.microsoft.com/en-us/graph/api/identitygovernance-userprocessingresult-summary?view=graph-rest-beta&tabs=powershell#request), [GO](https://learn.microsoft.com/en-us/graph/api/identitygovernance-userprocessingresult-summary?view=graph-rest-beta&tabs=go#request), and [PHP](https://learn.microsoft.com/en-us/graph/api/identitygovernance-userprocessingresult-summary?view=graph-rest-beta&tabs=php#request).

**Comment by CarolKigoonya** [comment]
Hi @msewaweru, this seems to be working as expected. Please confirm if the issue persists.

**Comment by msewaweru** [comment]
Confirmed that the example has been corrected.

**Comment by AlexFilipin** [comment]
#please-open
