### ISSUE TITLE
Investigate OpenAPI description for OData query parameters

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-devx-api#618]
https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/715/files

![image](https://user-images.githubusercontent.com/447694/123107564-a8654200-d407-11eb-8e43-f972e0796dd0.png)
This change does not seem correct. 
[AB#10024](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10024)

**Comment by irvinesunday** [comment]
@darrelmiller @peombwa @adhiambovivian 

The root cause is the updated [Expand](https://github.com/microsoft/OpenAPI.NET/blob/6bb23b6fee1d45d97bf47be0ce1ab3d20db74df5/src/Microsoft.OpenApi/Models/OpenApiParameter.cs#L77-L88) property in the `OpenApiParameter.cs` class in the `Microsoft.OpenApi.Models` namespace in the `v1.3.0-preview` of the `Microsoft.OpenApi` library, which DevX API is currently taking a dependency on. 
This seems to have been a bug fix on the said library, which correctly sets the `Explode` property to `true` when the `ParameterStyle` is set to `Form`. In [previous versions](https://github.com/microsoft/OpenAPI.NET/blob/553061a69b2d8b8b1653f172707409a16f2a9579/src/Microsoft.OpenApi/Models/OpenApiParameter.cs#L75-L82), the client would have to explicitly set this value. If the client failed to set this, the value would erroneously remain as `false`, even when the `ParameterStyle` is set to `Form`.

This change seems to be the expected outcome; `explode` should be true when the style is `form`

Do we want to revert to the initial state of `explode: false`? This can be done in DevX API within the `PowershellFormatter.cs` class.

**Comment by peombwa** [comment]
I believe we should explicitly set `explode` to `false` since that's how [all OData query parameters are used in Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#odata-system-query-options). e.g., `$select=id,displayName,givenName` mirrors what `explode: false` does. If `explode` were to be set to `true` (default for `style: form`), then the same `$select` would be  `$select=id&$select=displayName&$select=givenName`.

@darrelmiller, are there special cases that you know of where we use `explode: true` in Microsoft Graph?

On a related note, AutoREST.PowerShell doesn't respect the value set on `explode`, and it always generates query parameters as `explode: false` even when explode is explicitly set to true.
