### ISSUE TITLE
Add support for $count When Appended to a Url

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/microsoft-graph-devx-api#632]
Example:
```http
GET /contacts/{id}/transitiveReports/$count
```
generates 

```C#
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var int32 = await graphClient.Contacts["{orgContact-id}"].TransitiveReports.$count
	.Request()
	.GetAsync();
```
Instead of this:

```C#
var int32 = await graphClient.Contacts["{orgContactid}"].TransitiveReports.Count.Request() .GetAsync();
```
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/875
	 
[AB#10171](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10171)

**Comment by darrelmiller** [comment]
We need to investigate if OpenAPI.NET.OData will generate a path for this resource when the OData Capability annotations indicate that $count is supported.

Today, we can't fix this issue completely because we don't know which APIs support $count and therefore cannot know if the SDK actually supports the .Count method.

What we could do is update the code snippet generator to render the Count method and if the SDK doesn't support it, then Raptor will detect it and we can track the issue.

**Comment by adhiambovivian** [comment]
![image](https://user-images.githubusercontent.com/9458079/128191694-d75ef47e-3039-436a-b774-c37d46f72555.png)

More context from GE

**Comment by fey101** [comment]
This is actually a known issue in the SDK as well. https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/402. But as mentioned above the snippet generator, can be worked on to render the `Count` method correctly instead of prepending it with dollar sign.

**Comment by andrueastman** [comment]
Closing this for now as $count segments are supported in Kiota based versions of the SDK as captured in https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/402
