### ISSUE TITLE
The Snippet Generated Doesn't Match with Provided URL On FilterByCurrentUser Params.

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/microsoft-graph-devx-api#868]
http request:
```http
POST https://graph.microsoft.com/beta/identityGovernance/accessReviews/decisions/filterByCurrentUser(on='reviewer')/recordAllDecisions
Content-Type: application/json

{
  "decision": "Deny",
  "justification": "Alice switched teams and no longer works with this group",
  "principalId": "2043848d-e422-473c-8607-88a3319ff491",
  "resourceId": "733ef921-89e1-4d7e-aeff-83612223c37e"
}
```
Generated Snippet: 
```C#
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var decision = "Deny";

var justification = "Alice switched teams and no longer works with this group";

var principalId = "2043848d-e422-473c-8607-88a3319ff491";

var resourceId = "733ef921-89e1-4d7e-aeff-83612223c37e";

await graphClient.IdentityGovernance.AccessReviews.Decisions
	.FilterByCurrentUser(null)
	.RecordAllDecisions(decision,justification,principalId,resourceId)
	.Request()
	.PostAsync();
```

The filter by current user method generated doesn't contain the enum value of on='reviewer' which translates to `.FilterByCurrentUser(AccessReviewInstanceDecisionItemFilterByCurrentUserOptions.Reviewer)`

**Comment by andrueastman** [comment]
Closing this as this is fixed in the openApi based snippet generator and which handles enum options in the URL. 
Alternate examples at https://learn.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&tabs=csharp.

However, the snippet specifically fails to generate due to missing POST method in the API tracked via https://github.com/microsoftgraph/msgraph-metadata/issues/406
