### ISSUE TITLE
Generate code snippets for examples in conceptual articles

### ISSUE THREAD

**Issue by FaithOmbongi** [microsoftgraph/microsoft-graph-devx-api#880]
**Is your feature request related to a problem? Please describe. Describe the solution you'd like**
Currently, code snippets are generated only for examples in reference page types. We have several examples in conceptual page content (LEARN node) and these too need code snippets so that they shouldn't be manually created. Example: https://docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup

**Describe alternatives you've considered**
Manually creating code snippets. Not feasible.

**Additional context**
A while back, we had code snippets generated for conceptual pages. I don't know how they disappeared. But it would be great for the end-to-end developer guidance if we can have the feature re-implemeneted.

**Comment by FaithOmbongi** [comment]
Gentle ping @maisarissi, @zengin - do we have an ETA for this request? We're publishing a number of conceptual docs with examples and would love it if we can have the code snippets for those examples.

**Comment by andrueastman** [comment]
It looks like this page is a conceptual doc and has code snippets generated.

https://docs.microsoft.com/en-us/graph/outlook-calendar-online-meetings?tabs=http

This shows that APIDoctor does indeed scan and pick http examples from conceptual articles but for some reason some other conceptual pages are not picked up. 

This could be potentially due to either different formatting across the conceptual docs pages causing APIDoctor not to pick up the examples or a bug (or feature? 😅 ) in APIDoctor that makes the other pages get skipped. 
This would need some investigation to get to the cause.

**Comment by FaithOmbongi** [comment]
Hi @andrueastman, an investigation will be super helpful to find the root cause and see if we can resolve it through the structure of the conceptual doc. Thanks.

**Comment by maisarissi** [comment]
Hello everyone.

I created an issue on the APIDoctor repo requesting further investigation based on @andrueastman comment.

**Comment by FaithOmbongi** [comment]
Hi @maisarissi, any update resolving this issue?

**Comment by andrueastman** [comment]
Looks like the code was updated to only process snippets in the `/api-reference/beta` or `/api-reference/v1.0` folders of the docs repo. 

https://github.com/OneDrive/apidoctor/pull/155 has been authored to resolve.
